---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend
  namespace: three-tier
spec:
  minReadySeconds: 3
  replicas: 2
  selector:
    matchLabels:
      role: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%      
  template:
    metadata:
      name: front
      labels: 
        role: frontend
    spec:
      containers:
        - image: meena835/tws:frontend
          name: tws
          env:
          - name: REACT_APP_BACKEND
            value: "api:3500"
          ports:
            - containerPort: 3000
                
    
---
apiVersion: v1
kind: Service
metadata:
  name: ss
  namespace: three-tier
spec: 
  type: LoadBalancer
  selector:
    role: frontend
  ports:
    - protocol: TCP
      port: 30000
      targetport: 3000  
