apiVersion: v1
kind: Service
metadata:
  name: ss
  namespace: three-tier
spec: 
  type: LoadBalancer
  selector:
    role: frontend
  ports:
    - protocol: TCP
      port: 30000
      targetport: 3000    
